### ISSUE TITLE
Spindle on/off button not working, sort of

### ISSUE THREAD

**Issue by Ozzy62** [vlachoudis/bCNC#103]
When opening bCNC the spindle on/off button does not work. M3/M5 on the commandline works ok.
Opening a file and starting and stopping it again makes the spindle on/off button working. Is that a bug ?.

**Comment by vlachoudis** [comment]
I've just updated the interface with a completely new look and functionality. And this problem should be not be there. Could you please confirm?

**Comment by Ozzy62** [comment]
Tried the latest version but it will not run , complaining about:
   File "./bCNC.py", line 8
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax

**Comment by Ozzy62** [comment]
Tried the latest version but it will not run , complaining about:
   File "./bCNC.py", line 8
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax

**Comment by vlachoudis** [comment]
Please re-download again. During the merge of the two branches I've got this conflicts inside the files, but it was corrected some minutes ago.

**Comment by Ozzy62** [comment]
Sorry to say that the problem is still there. I am running bCNC on a Raspberry Pi 2, if that makes a difference.

**Comment by vlachoudis** [comment]
Just for confirmation, clicking the Spindle button sends a M3/M5 command it will not start the spindle if the RPM on the slider is not set.

**Comment by Ozzy62** [comment]
I do not see any M3/5 commands in the terminal. But loading a file and starting/stopping will make M3/5 commands from the spindle button visible in the terminal window. And yes I do have set a speed on the spindle.

**Comment by vlachoudis** [comment]
Ok I will check on my machine

**Comment by vlachoudis** [comment]
I've just tested it on my machine, and I it works Ok. Does your grbl goes on Hold state when it reboots and then bCNC doesn't send any command. Did you unlock first?

**Comment by Ozzy62** [comment]
Sorry. I did not do the unlock thingy. It works perfectly ok when having unlocked. 
Have you any clue on why I cant get the latest, and greatest, version to work ?.

**Comment by vlachoudis** [comment]
Ok, no problem, good to know what was the issue :)

Can you be more explicit what is the problem with the new version?

**Comment by Ozzy62** [comment]
When executing sh bCNC from a terminal i get the following:
File "./bCNC.py", line 8
<<<<<<< HEAD
^
SyntaxError: invalid syntax

Doing the same on a older version works ok, the program starts ok.

**Comment by vlachoudis** [comment]
As I mentioned before, please re-download the program either the zip from github or with the git clone https://github.com/vlachoudis/bCNC
